# AUTOGENERATED STUB — M05_evidence_builder
"""Select two distinct sentences + lineage.
I/O: CleanDoc -> EvidenceCard
"""
from typing import Any, Dict, Optional
try:
    from nww_models import *
except Exception:  # pragma: no cover
    # Allow import even if models are not generated yet
    pass

def run(input_obj, **kwargs):
    """Run M05_evidence_builder. Replace with real logic.
    Args:
        input_obj: CleanDoc
    Returns:
        EvidenceCard
    """
    raise NotImplementedError("M05_evidence_builder is a stub. Implement me.")
