# config/scoring.yaml
combine: linear        # linear | noisy_or
weights:
  indicator: 0.6       # Gate(indicator) 비중
  dbn: 0.4             # DBN 예측 비중
severity:
  low: 0.30
  medium: 0.55
  high: 0.75
shift_delta: 0.15      # 전후 fused_score 변화량 임계치
