# FastAPI mount helper for generated GraphQL schema
from fastapi import APIRouter
from strawberry.fastapi import GraphQLRouter
from api.graphql_gen.schema import schema  # generated by codegen_graphql.py

def get_router() -> APIRouter:
    return GraphQLRouter(schema)
